services:
  db:
    image: postgres:15
    container_name: wallet-db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: walletdb
    ports:
      - "5432:5432"
  redis:
    image: redis:7.0-alpine
    container_name: wallet-redis
    ports:
      - "6379:6379"